import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Navigation from '@/app/components/layout/Navigation/Navigation'
import Information from '@/app/components/screens/information/Information'
import Destination from '@/app/components/screens/destination/Destination'
import Rooms from '@/app/components/screens/rooms/Rooms'
import dynamic from 'next/dynamic'
const inter = Inter({ subsets: ['latin'] })
const ReactMap = dynamic(() => import("../app/components/screens/map/Map"), {
  ssr: false
});



export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v2.14.1/mapbox-gl.css' rel='stylesheet' />
      </Head>
      <Navigation />
      <main className={styles.main}>
        <Information />
        {/* <Rooms /> */}
        {/* <ReactMap /> */}
        <Destination />
      </main>
    </>
  )
}
